// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBeSlL5PZP-0GQ17dAdpS7kK1J6XKO5hM',
    appId: '1:650727221383:web:a1b767b53bfcf89b317022',
    messagingSenderId: '650727221383',
    projectId: 'todolist-91a88',
    authDomain: 'todolist-91a88.firebaseapp.com',
    storageBucket: 'todolist-91a88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC7eXEVFVaRh5F8dtQhMQTtwMqTKsRNZs',
    appId: '1:650727221383:android:ab92b6f11a81a28c317022',
    messagingSenderId: '650727221383',
    projectId: 'todolist-91a88',
    storageBucket: 'todolist-91a88.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBeSlL5PZP-0GQ17dAdpS7kK1J6XKO5hM',
    appId: '1:650727221383:web:930b517f15aa5c91317022',
    messagingSenderId: '650727221383',
    projectId: 'todolist-91a88',
    authDomain: 'todolist-91a88.firebaseapp.com',
    storageBucket: 'todolist-91a88.appspot.com',
  );
}
